### ISSUE TITLE
precice/fenics-adapter:latest is not stable but the develop release

### ISSUE THREAD

**Issue by valentin-seitz** [precice/fenics-adapter#160]
Contrary to expectation the docker container published with tag `latest` seems to be the same as `develop`. 
It should however use the main/master to build. 
We need this to have a stable version compatible with precicev2 to test in the system tests.

**Comment by MakisH** [comment]
As we just discussed, here is the problem:

https://github.com/precice/fenics-adapter/blob/0a8f031b59f8b61af650a5e508a452a45165f56e/.github/workflows/build-docker.yml#L34

The GitHub Action *always* pushes to `latest`. This should only be true for the `master` branch, especially since there is a separate `develop` tag.

I suggest:
- Updating the workflow to actually only push to `latest` when then branch is `master`
- Updating the image manually for now

@IshaanDesai is there anything that relies on the `latest` tag of this image at the moment? Can we go ahead and do the above steps?

**Comment by IshaanDesai** [comment]
> @IshaanDesai is there anything that relies on the `latest` tag of this image at the moment? Can we go ahead and do the above steps?

Not to my knowledge no. You can go ahead and do the above steps.
