### ISSUE TITLE
Allow One Way Coupling

### ISSUE THREAD

**Issue by richahert** [precice/fenics-adapter#69]
Currently the adapter expects 2-way coupling: reading and writing. For aste I want to read only, so there are a few small changes needed.

**Comment by BenjaminRueth** [comment]
Please take a look at the interface changes that we are preparing in #37. Does this work for you? If not, can you add a comment to the PR what you would need? I think adding one-way-coupling into the current develop version of the adapter is not really worth the effort, since we are changing it a lot in #37.
